#!/usr/bin/env bash
#Display the content of file /etc/pass

passwd="/etc/passwd"
while IFS=':' read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIRECTORY COMMAND
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"
done < "$passwd"
